'use client';
import {
  Navbar,
  NavbarBrand,
  NavbarContent,
  NavbarItem,
  Link,
  Button,
} from '@nextui-org/react';
import './globals.css';
import { Inter } from 'next/font/google';
import { Providers } from './providers';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Turborepo',
//   description: 'Generated by create turbo',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html className="dark" lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="h-screen flex flex-col">
            <div>
              <Navbar>
                <NavbarBrand>
                  <p className="font-bold text-inherit">ACME</p>
                </NavbarBrand>
                <NavbarContent
                  className="hidden sm:flex gap-4"
                  justify="center"
                >
                  <NavbarItem>
                    <Link color="foreground" href="#">
                      Features
                    </Link>
                  </NavbarItem>
                  <NavbarItem isActive>
                    <Link aria-current="page" href="#">
                      Customers
                    </Link>
                  </NavbarItem>
                  <NavbarItem>
                    <Link color="foreground" href="#">
                      Integrations
                    </Link>
                  </NavbarItem>
                </NavbarContent>
                <NavbarContent justify="end">
                  <NavbarItem className="hidden lg:flex">
                    <Link href="#">Login</Link>
                  </NavbarItem>
                  <NavbarItem>
                    <Button as={Link} color="primary" href="#" variant="flat">
                      Sign Up
                    </Button>
                  </NavbarItem>
                </NavbarContent>
              </Navbar>
            </div>
            <div className="flex-1">{children}</div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
